language: cpp

before_install:
  - chmod +x get_code_cov.sh
  
script: 
- make
- get_code_cov

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
